---
- hosts: all
  become: yes
  gather_facts: yes
  tags: users
  tasks:
    - name: Create new users
      user:
        name: "{{ item.name }}"
        uid:  "{{ item.uid }}"
        state: present
      loop:
        - name: allemand
          uid: 1020
        - name: anglais
          uid: 1030
        - name: espagnol
          uid: 1040

