---

# l'instruction when accepte aussi la recherche d'un élément dans une liste :
# when: ansible_distribution in [ "Ubuntu" , "Debian" ]
# mais aussi les opérateurs logiques "and" "or"
# when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"
 
- hosts: all
  gather_facts: true
  tasks:


  - name: install apache et php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes


