---

- hosts: all
  become: true
  pre_tasks:

  - name: Updates repo cache (CentOS and AlmaLinux)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in [ "CentOS","AlmaLinux" ]
 
  - name: Update repo cache (Ubuntu and Debian)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution in ["Ubuntu","Debian","Kali GNU/Linux"]

- hosts: redhat_servers
  gather_facts: False
  become: true
  roles:
    - base

##- hosts: workstations
##  gather_facts: False
##  become: true
##  roles:
##    - workstations
##
##- hosts: all
##  become: true
##  roles:
##    - security_tools
##
##- hosts: web_servers
##  gather_facts: False
##  become: true
##  roles:
##    - web_servers
##
##
##- hosts: db_servers
##  gather_facts: False
##  become: true
##  roles:
##    - db_servers
##
##
##- hosts: file_servers
##  gather_facts: False
##  become: true
##  roles:
##    - file_servers
##
##- hosts: mail_servers
##  gather_facts: False
##  become: true
##  roles:
##    - mail_servers
##
