- name: Install postfix and mailutils package
  tags: mail,postfix
  package:
    name:
      - "{{ mail_package_name }}"
      - "{{ mta_package_name }}"
    state: latest

# sur Ubuntu, Debian, on install postfix, puis on utilise debconf pour reconfigurer le package
# Fichier supplémentaire à traiter pour Ubuntu et Debian : /etc/mailname qui contient le nom du serveur local
 
- name: Install debconf-utils
  package:
    name:
      - debconf-utils
    state: latest
  when: ansible_distribution in [ "Ubuntu" , "Debian" ]

- name: Configuration de Postfix
  debconf:
    name: postfix
    question: "postfix/main_mailer_type"
    value: "Internet Site"
    vtype: "string"
  when: ansible_distribution in [ "Ubuntu" , "Debian" ]

