- name: Add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPFfuCw/rJo2Itw0YFdq6MtY7zP55nBKpxxOty8Y0xeIw2s5toi+JEucNFbnMx68hM8m8IYww+n7ePeQ9RayHKSrPAAIh3Q0MwMSZ+p232a+th5I1gmbaOktHPFAFothqgdsnEjpGUR1RxjxUgEJ9WDIg1XUF4gDHwTisPj2d5s8j7hYq+eIYJ1ftqMxEFWWNz8o8wn1p48c99lrJea74fPpZ2TOuXyOSBhA3E+xq7L2gDlUG7JOD+uUs5XRw1tU6W5iYEL+0pMGKCNz9AAYwv03BkspvAsff4sU6gPb8EA+VyApdNuZ5IJJs900wOHM5biNawzdfG0upGp5advxpd ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
